[package]
name = "serde-mml"
version = "0.1.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0.110"
base64 = "0.12.1"
thiserror = "1.0.17"

[dev-dependencies]
proptest = "0.9.6"
